import type { BookingDoctor } from './types';
export const localDoctors: BookingDoctor[] = [
  {
    id: 1,
    name: 'dr. Yoshi Wijaya, Sp.KK',
    title: 'Spesialis Kulit & Kelamin',
    specialization: 'Dermatologist & Laser Specialist',
    phone: '081211462862',
    experience: '8+ Tahun Pengalaman',
    rating: 4.9,
    review_count: 142,
    avatar_color: 'from-rose-400 to-pink-500',
    bio: 'Fokus pada penanganan jerawat inflamasi, bekas luka atrophic, dan peremajaan kulit modern.',
    skills: ['Laser Treatment', 'Acne Scar Subcision', 'Medical Peeling', 'Anti-Aging Injectables'],
    schedule_days: 'Senin - Jumat',
    available_days: [1, 2, 3, 4, 5],
    work_start_time: '10:00',
    work_end_time: '20:00',
    status: 'active',
  },
  {
    id: 2,
    name: 'dr. Sinta Rahmawati, Sp.DV',
    title: 'Spesialis Dermatologi & Venereologi',
    specialization: 'Anti-Aging & Melasma Expert',
    phone: '081211462862',
    experience: '10+ Tahun Pengalaman',
    rating: 4.9,
    review_count: 198,
    avatar_color: 'from-amber-400 to-rose-400',
    bio: 'Ahli terapi hiperpigmentasi membandel, melasma hormonal, dan skin barrier restoration.',
    skills: ['Melasma Therapy', 'Pico Laser', 'Skin Barrier Repair', 'Collagen Booster'],
    schedule_days: 'Selasa - Sabtu',
    available_days: [2, 3, 4, 5, 6],
    work_start_time: '10:00',
    work_end_time: '20:00',
    status: 'active',
  },
  {
    id: 3,
    name: 'dr. Alana Christie, Sp.KK',
    title: 'Dokter Estetika Klinis',
    specialization: 'Clinical Aesthetic Physician',
    phone: '081211462862',
    experience: '6+ Tahun Pengalaman',
    rating: 4.8,
    review_count: 110,
    avatar_color: 'from-emerald-400 to-teal-500',
    bio: 'Mengedepankan perawatan preventif, glowing radiant finish, dan formulasi home-care presisi.',
    skills: ['Glow Peeling', 'Hydrafacial Pro', 'Botox & Contour', 'Custom Serum Therapy'],
    schedule_days: 'Senin - Kamis & Sabtu',
    available_days: [1, 2, 3, 4, 6],
    work_start_time: '10:00',
    work_end_time: '20:00',
    status: 'active',
  },
];
