import { API_BASE_URL } from '../client';
import { describeFailure, type ErrorBody } from '../errors';

/* ==========================================================================
   Admin Treatment (Clinic Service) Management Interfaces & API Functions
   ========================================================================== */

export interface AdminServiceItem {
  id: number;
  code: string;
  name: string;
  description: string | null;
  category: string | null;
  duration_minutes: number;
  price: string | number;
  is_active: boolean;
  appointments_count?: number;
  created_at?: string;
  updated_at?: string;
}

export interface AdminServicePayload {
  name: string;
  category?: string | null;
  description?: string | null;
  duration_minutes: number;
  price: number;
  is_active?: boolean;
}

async function request<T>(
  path: string,
  token: string,
  fallbackError: string,
  init: { method?: string; body?: unknown } = {}
): Promise<T> {
  const res = await fetch(`${API_BASE_URL}/admin/services${path}`, {
    method: init.method ?? 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: `Bearer ${token}`,
      ...(init.body !== undefined ? { 'Content-Type': 'application/json' } : {}),
    },
    body: init.body !== undefined ? JSON.stringify(init.body) : undefined,
    cache: 'no-store',
  });

  if (!res.ok) {
    const errorJson = (await res.json().catch(() => null)) as ErrorBody | null;
    throw new Error(describeFailure(errorJson, `${fallbackError} (${res.status})`));
  }

  return (await res.json().catch(() => ({}))) as T;
}

/**
 * Fetch every treatment, including inactive ones, with its booking count.
 */
export async function fetchAdminServices(token: string): Promise<AdminServiceItem[]> {
  const json = await request<{ data: AdminServiceItem[] }>('', token, 'Gagal memuat layanan');
  return json.data;
}

/**
 * Create a treatment. The code is generated by the server.
 */
export async function adminCreateService(
  payload: AdminServicePayload,
  token: string
): Promise<AdminServiceItem> {
  const json = await request<{ data: AdminServiceItem }>('', token, 'Gagal membuat layanan', {
    method: 'POST',
    body: payload,
  });
  return json.data;
}

/**
 * Update a treatment.
 */
export async function adminUpdateService(
  id: number,
  payload: Partial<AdminServicePayload>,
  token: string
): Promise<AdminServiceItem> {
  const json = await request<{ data: AdminServiceItem }>(`/${id}`, token, 'Gagal memperbarui layanan', {
    method: 'PUT',
    body: payload,
  });
  return json.data;
}

/**
 * Toggle whether the treatment can be booked.
 */
export async function adminToggleService(id: number, token: string): Promise<AdminServiceItem> {
  const json = await request<{ data: AdminServiceItem }>(`/${id}/toggle`, token, 'Gagal mengubah status layanan', {
    method: 'PATCH',
  });
  return json.data;
}

/**
 * Delete a treatment that has never been booked.
 */
export async function adminDeleteService(id: number, token: string): Promise<void> {
  await request<unknown>(`/${id}`, token, 'Gagal menghapus layanan', { method: 'DELETE' });
}
